package com.ruuvi.station.bluetooth.contract

data class FoundRuuviTag (
    var id: String? = null,
    var url: String? = null,
    var rssi: Int? = null,
    var temperature: Double? = null,
    var humidity: Double? = null,
    var pressure: Double? = null,
    var accelX: Double? = null,
    var accelY: Double? = null,
    var accelZ: Double? = null,
    var voltage: Double? = null,
    var dataFormat: Int? = null,
    var txPower: Double? = null,
    var movementCounter: Int? = null,
    var measurementSequenceNumber: Int? = null,
    var connectable: Boolean? = null,
    var pm1: Double? = null,
    var pm25: Double? = null,
    var pm4: Double? = null,
    var pm10: Double? = null,
    var co2: Int? = null,
    var voc: Int? = null,
    var nox: Int? = null,
    var luminosity: Int? = null,
    var dBaAvg: Double? = null,
    var dBaPeak: Double? = null,
)