apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

android {
    compileSdk 37

    namespace 'com.ruuvi.station.bluetooth.def'

    defaultConfig {
        minSdkVersion 23
        targetSdkVersion 37
        versionCode 10811
        versionName "1.8.11"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables.useSupportLibrary = true
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    kotlinOptions {
        jvmTarget = "11"
    }
    testOptions {
        targetSdk 37
    }
    lint {
        targetSdk 37
    }
}

def kodein_version = "6.5.0"

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')

    implementation libs.nv.bluetooth
    implementation libs.ble.ktx

    implementation libs.kotlin.stdlib

    implementation libs.timber
    implementation libs.core.ktx
    implementation libs.semver

    implementation libs.timber
    implementation(libs.work.runtime.ktx)

    implementation libs.kodein.di
    implementation libs.kodein.di.framework.android.x
}